import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import Link from "next/link";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <header>
          <h1>The App</h1>
          <nav>
            <Link href={"/"}>Home</Link> | <Link href={"/about"}>About</Link> |{" "}
            <Link href={"/posts"}>Posts</Link>
          </nav>
        </header>
        {children}
        <footer>MMXXV</footer>
      </body>
    </html>
  );
}
